class Autogenerated {
  List<AutogeneratedItem> rows;
  int total;
  String statusCode;
  String message;
  Autogenerated({this.statusCode, this.message,this.rows, this.total});

  Autogenerated.fromJson(Map<String, dynamic> json) {
statusCode = json['statusCode'];
message = json['message'];
    if (json['rows'] != null) {
      rows = [];//AutogeneratedItem>();
      json['rows'].forEach((v) {
        rows.add(new AutogeneratedItem.fromJson(v));
      });
    }
    total = json['total'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['statusCode'] = this.statusCode;
    data['message'] = this.message;
    if (this.rows != null) {
      data['rows'] = this.rows.map((v) => v.toJson()).toList();
    }
    data['total'] = this.total;
    return data;
  }
}

class AutogeneratedItem {
  String textOne;
  String urlOne;

  AutogeneratedItem({this.textOne, this.urlOne});

  AutogeneratedItem.fromJson(Map<String, dynamic> json) {
    textOne = json['textOne'];
    urlOne = json['urlOne'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['textOne'] = this.textOne;
    data['urlOne'] = this.urlOne;
    return data;
  }
}
