
class RoomListPayload {
  int? roomInstitutionId;
  int? memberId;
  String? memberType;
  bool? isPrivate;
  String? searchVal;
  int? pageSize;
  int? pageNumber;
  bool? isOwn;
  String? requestedByType;
  int? requestedById;
  int? institutionId;
  String? roomType;
  String? roomPrivacyType;

  RoomListPayload(
      {this.roomInstitutionId,
      this.memberId,
      this.memberType,
      this.isPrivate,
      this.searchVal,
      this.pageSize,
        this.isOwn,
        this.requestedById,
        this.requestedByType,
      this.pageNumber,
        this.roomType,
        this.roomPrivacyType,
      this.institutionId});

  RoomListPayload.fromJson(Map<String, dynamic> json) {
    roomInstitutionId = json['room_business_id'];
    memberId = json['member_id'];
    isOwn = json['is_own'];
    requestedByType = json['requested_by_type'];
    requestedById = json['requested_by_id'];
    memberType = json['member_type'];
    isPrivate = json['is_private'];
    searchVal = json['searchVal'];
    pageSize = json['page_size'];
    pageNumber = json['page_number'];
    institutionId = json['business_id'];
    roomType = json['room_type'];
    roomPrivacyType =json['room_privacy_type'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['room_business_id'] = this.roomInstitutionId;
    data['member_id'] = this.memberId;
    data['is_own'] = this.isOwn;
    data['requested_by_id'] = this.requestedById;
    data['requested_by_type'] = this.requestedByType;
    data['member_type'] = this.memberType;
    data['is_private'] = this.isPrivate;
    data['searchVal'] = this.searchVal;
    data['page_size'] = this.pageSize;
    data['page_number'] = this.pageNumber;
    data['business_id'] = this.institutionId;
    data['room_type'] = this.roomType;
    data['room_privacy_type'] = this.roomPrivacyType;
    return data;
  }
}



class RoomListResponse {
  String? statusCode;
  String? message;
  List<RoomListItem>? rows;
  int? total;

  RoomListResponse({this.statusCode, this.message, this.rows, this.total});

  RoomListResponse.fromJson(Map<String, dynamic> json) {
    statusCode = json['statusCode'];
    message = json['message'];
    if (json['rows'] != null) {
      rows = [];//RoomListItem>();
      json['rows'].forEach((v) {
        rows!.add(new RoomListItem.fromJson(v));
      });
    }
    total = json['total'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['statusCode'] = this.statusCode;
    data['message'] = this.message;
    if (this.rows != null) {
      data['rows'] = this.rows!.map((v) => v.toJson()).toList();
    }
    data['total'] = this.total;
    return data;
  }
}

class RoomListItem {
  int? id;
  bool? isEvent;
  bool? isRequestedByMember;
  String? roomOwnerType;
  int? roomOwnerTypeId;
  int? roomInstitutionId;
  String? roomName;
  String? roomDescription;
  bool? isPrivate;
  bool? isSharable;
  String? roomStatus;
  String? roomType;
  String? roomCreatedByType;
  int? roomCreatedById;
  int? membersCount;
  String? membershipStatus;
  String? memberRoleType;
  String? roomProfileImageUrl;
  bool? isAutoGeneratedRoom;
  Header? header;
  List<MembersList>? membersList;
  String? roomPrivacyType;
  List<String>? roomTopics;
  OtherDetails? otherDetails;

  RoomListItem(
      {this.id,
      this.roomOwnerType,
      this.roomOwnerTypeId,
      this.roomInstitutionId,
      this.roomName,
        this.isEvent,
        this.isRequestedByMember,
      this.roomDescription,
      this.isPrivate,
      this.isSharable,
      this.roomStatus,
      this.roomType,
      this.roomCreatedByType,
      this.roomCreatedById,
      this.membersCount,
      this.membershipStatus,
      this.memberRoleType,
        this.isAutoGeneratedRoom,
        this.header,
        this.membersList,
        this.otherDetails,
        this.roomPrivacyType, this.roomTopics,
      this.roomProfileImageUrl});

  RoomListItem.fromJson(Map<String, dynamic> json) {
    id = json['id'];
    isRequestedByMember = json['is_requested_by_member'];
    roomOwnerType = json['room_owner_type'];
    roomOwnerTypeId = json['room_owner_type_id'];
    roomInstitutionId = json['room_business_id'];
    roomName = json['room_name'];
    roomDescription = json['room_description'];
    isPrivate = json['is_private'];
    isSharable = json['is_sharable'];
    roomStatus = json['room_status'];
    roomType = json['room_type'];
    roomCreatedByType = json['room_created_by_type'];
    roomCreatedById = json['room_created_by_id'];
    membersCount = json['members_count'];
    membershipStatus = json['membership_status'];
    memberRoleType = json['member_role_type'];
    roomProfileImageUrl = json['room_profile_image_url'];
    isAutoGeneratedRoom = json['is_auto_created'];
    roomPrivacyType = json['room_privacy_type'];
    roomTopics = json['room_topics']!=null?json['room_topics'].cast<String>():null;
    header = json['header'] != null ? new Header.fromJson(json['header']) : null;
    if (json['members_list'] != null) {
      membersList = [];//MembersList>();
      json['members_list'].forEach((v) {membersList!.add(new MembersList.fromJson(v));});
    }
    otherDetails = json['other_details'] != null
        ? new OtherDetails.fromJson(json['other_details'])
        : null;
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['id'] = this.id;
    data['is_requested_by_member']=this.isRequestedByMember;
    data['room_owner_type'] = this.roomOwnerType;
    data['room_owner_type_id'] = this.roomOwnerTypeId;
    data['room_business_id'] = this.roomInstitutionId;
    data['room_name'] = this.roomName;
    data['room_description'] = this.roomDescription;
    data['is_private'] = this.isPrivate;
    data['is_sharable'] = this.isSharable;
    data['room_status'] = this.roomStatus;
    data['room_type'] = this.roomType;
    data['room_created_by_type'] = this.roomCreatedByType;
    data['room_created_by_id'] = this.roomCreatedById;
    data['members_count'] = this.membersCount;
    data['membership_status'] = this.membershipStatus;
    data['member_role_type'] = this.memberRoleType;
    data['room_profile_image_url'] = this.roomProfileImageUrl;
    data['is_auto_created'] = this.isAutoGeneratedRoom;
    data['room_privacy_type'] = this.roomPrivacyType;
    data['room_topics'] = this.roomTopics;
    if (this.header != null) {
      data['header'] = this.header!.toJson();
    }
    if (this.membersList != null) {
      data['members_list'] = this.membersList!.map((v) => v.toJson()).toList();
    }
    if (this.otherDetails != null) {
      data['other_details'] = this.otherDetails!.toJson();
    }
    return data;
  }
}
class OtherDetails {
  double? rating;
  bool? isRated;
  int? totalRatedUsers;

  OtherDetails({this.rating, this.isRated, this.totalRatedUsers});

  OtherDetails.fromJson(Map<String, dynamic> json) {
    rating = json['rating'];
    isRated = json['is_rated'];
    totalRatedUsers = json['total_rated_users'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['rating'] = this.rating;
    data['is_rated'] = this.isRated;
    data['total_rated_users'] = this.totalRatedUsers;
    return data;
  }
}

class Header {
  String? title;
  List<Action>? action;
  String? avatar;
  double? rating;
  String? subtitle1;
  bool? isVerified;

  Header(
      {this.title,
        this.action,
        this.avatar,
        this.rating,
        this.subtitle1,
        this.isVerified});

  Header.fromJson(Map<String, dynamic> json) {
    title = json['title'];
    if (json['action'] != null) {
      action = [];//Action>();
      json['action'].forEach((v) {
        action!.add(new Action.fromJson(v));
      });
    }
    avatar = json['avatar'];
    rating = json['rating'];
    subtitle1 = json['subtitle1'];
    isVerified = json['is_verified'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['title'] = this.title;
    if (this.action != null) {
      data['action'] = this.action!.map((v) => v.toJson()).toList();
    }
    data['avatar'] = this.avatar;
    data['rating'] = this.rating;
    data['subtitle1'] = this.subtitle1;
    data['is_verified'] = this.isVerified;
    return data;
  }
}

class Action {
  String? type;
  bool? value;

  Action({this.type, this.value});

  Action.fromJson(Map<String, dynamic> json) {
    type = json['type'];
    value = json['value'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['type'] = this.type;
    data['value'] = this.value;
    return data;
  }
}

class MembersList {
  String? name;
  String? profileImage;

  MembersList({this.name, this.profileImage});

  MembersList.fromJson(Map<String, dynamic> json) {
    name = json['name'];
    profileImage = json['profile_image'];
  }

  Map<String, dynamic> toJson() {
    final Map<String, dynamic> data = new Map<String, dynamic>();
    data['name'] = this.name;
    data['profile_image'] = this.profileImage;
    return data;
  }
}
